In [33]:
#Question3
#partII
import numpy as np
from numpy.linalg import eig

def findEigen(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors

matrixA = np.array([[2, 2, 4], [1, 3, 5],[2, 3, 4]])

eigenvalues, eigenvectors = findEigen(matrixA)       #calling the function

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [ 8.80916362  0.92620912 -0.73537273]
Eigenvectors:
 [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]


In [2]:
#Question3
#partIII
#a)

import numpy as np
from numpy.linalg import eig

def findEigen(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors
    
R = 0.02  # radius in meters
M = 10.0  # mass in kg

# Moment of inertia tensor for a sphere
Moment_of_inertiaX = (2/5) * M * R**2
Moment_of_inertiaY = Moment_of_inertiaX
Moment_of_inertiaZ = Moment_of_inertiaX

# Printing the calculated moments of inertia
print("Moments of inertia in x direction:",Moment_of_inertiaX,"kg m^2")
print("Moments of inertia in x direction:",Moment_of_inertiaX,"kg m^2")
print("Moments of inertia in x direction:",Moment_of_inertiaX,"kg m^2")
print()

# Eigenvalues and eigenvectors
matrixA = np.array([[Moment_of_inertiaX, Moment_of_inertiaY, Moment_of_inertiaZ],
                    [0,0,0],
                    [0,0,0]])

eigenvalues, eigenvectors = findEigen(matrixA)       #calling the function

print("Eigenvalues:", eigenvalues)
print()
print("Eigenvectors:\n", eigenvectors)


Moments of inertia in x direction: 0.0016 kg m^2
Moments of inertia in x direction: 0.0016 kg m^2
Moments of inertia in x direction: 0.0016 kg m^2

Eigenvalues: [0.0016 0.     0.    ]

Eigenvectors:
 [[ 1.         -0.70710678 -0.70710678]
 [ 0.          0.70710678  0.        ]
 [ 0.          0.          0.70710678]]


In [1]:
#Question3
#partIII
#b)
import numpy as np
from numpy.linalg import eig

def Hamiltonian(i, j):
    return 0.5 * (i + j) * np.sqrt(2)

matrixA = np.zeros((3, 3))      #Creating a blank matrix

for i in range(1, 4):        #obtaining values from the equation and assigning to the matrixA
    for j in range(1, 4):
        matrixA[i-1, j-1] = Hamiltonian(i, j)

eigenvalues, eigenvectors = eig(matrixA)        #calculating eigenvalues and eigenvaectors


print("Hamiltonian matrix:\n", matrixA)
print()
print("Eigenvalues of the Hamiltonian matrix:\n", eigenvalues)
print()
print('Eigenvectors of the Hamiltonian matrix:\n', eigenvectors)

Hamiltonian matrix:
 [[1.41421356 2.12132034 2.82842712]
 [2.12132034 2.82842712 3.53553391]
 [2.82842712 3.53553391 4.24264069]]

Eigenvalues of the Hamiltonian matrix:
 [ 8.82521638e+00 -3.39935008e-01 -2.16226403e-16]

Eigenvectors of the Hamiltonian matrix:
 [[-0.43036222 -0.80506005  0.40824829]
 [-0.56654216 -0.11119045 -0.81649658]
 [-0.70272209  0.58267915  0.40824829]]
