In [77]:
#Question2
#partII
import numpy as np
import numpy.linalg 
import math

matrixA = [[1,6,7],[5,9,-2],[3,4,0]]
matrixB = [[-2,3,1],[8,-2,3],[6,-3,-6]]

print("Matrix A:\n",matrixA)
print("Matrix B:\n",matrixB)
print()

print("A+B:\n",np.add(matrixA,matrixB))    #this means matrixA+matrixB 
print()

print("Determinant of matrix A:",np.linalg.det(matrixA))
print()
print("Transporse of matrix A:\n",np.transpose(matrixA))
print()

#checking weather matrix A is symmetric
if(np.array_equal(np.transpose(matrixA), matrixA)):
    print("Matrix A is symmetric")
else:
    print("Matrix A is not symmetric")
print()

print("Product of the two matrices:\n",numpy.dot(matrixA, matrixB))

Matrix A:
 [[1, 6, 7], [5, 9, -2], [3, 4, 0]]
Matrix B:
 [[-2, 3, 1], [8, -2, 3], [6, -3, -6]]

A+B:
 [[-1  9  8]
 [13  7  1]
 [ 9  1 -6]]

Determinant of matrix A: -77.00000000000001

Transporse of matrix A:
 [[ 1  5  3]
 [ 6  9  4]
 [ 7 -2  0]]

Matrix A is not symmetric

Product of the two matrices:
 [[ 88 -30 -23]
 [ 50   3  44]
 [ 26   1  15]]


In [2]:
#partIII
#a
import numpy as np
import numpy.linalg 
import math

matrixX = [[math.cos(np.pi/6)],[math.sin(np.pi/6)]]
matrixY = [[math.sin(np.pi/6)],[-math.cos(np.pi/6)]]

A=numpy.dot(matrixX, np.transpose(matrixX))+numpy.dot(matrixY, np.transpose(matrixY))
print("matrix A:\n",A)

matrix A:
 [[1. 0.]
 [0. 1.]]



In [4]:
#b
matrixC = [[2,1,-3],[1,2,-3],[-3,-3,-3]]
print("C:",matrixC)
print()

print("Transporse of matrix C:\n",np.transpose(matrixC))
print()

if(np.array_equal(np.transpose(matrixC), matrixC)):
    print("Matrix C is symmetric")
else:
    print("Matrix C is not symmetric")
print()

C: [[2, 1, -3], [1, 2, -3], [-3, -3, -3]]

Transporse of matrix C:
 [[ 2  1 -3]
 [ 1  2 -3]
 [-3 -3 -3]]

Matrix C is symmetric



In [2]:
#c
import numpy as np

# Defining the parameters
alpha = np.pi / 3
beta = np.pi / 4
delta = np.pi / 4
gamma = 3 * np.pi / 2

i = 1j    #complex number 

expiAlpha = np.exp(i * alpha)

matrix1 = np.array([
    [np.exp(-i * beta / 2), 0],
    [0, np.exp(i * beta / 2)]
])
matrix2 = np.array([
    [np.cos(gamma / 2), -np.sin(gamma / 2)],
    [np.sin(gamma / 2), np.cos(gamma / 2)]
])
matrix3 = np.array([
    [np.exp(-i * delta / 2), 0],
    [0, np.exp(-i * delta / 2)]
])

matrixU = expiAlpha * np.dot(np.dot(matrix1, matrix2), matrix3)
print("Matrix U:\n",matrixU)


Matrix U:
 [[-0.6830127 -0.1830127j  -0.6830127 -0.1830127j ]
 [ 0.35355339+0.61237244j -0.35355339-0.61237244j]]
